//! Data models for the `auth` OpenAPI group and `/api/me`.

use serde::{Deserialize, Serialize};

/// Login request for `/api/auth/login` and `/api/auth/login/hash`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoginReq {
    /// Username.
    pub username: String,
    /// Password, or static SHA-256 hash for `/login/hash`.
    pub password: String,
    /// Optional two-factor authentication code.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub otp_code: Option<String>,
}

/// Successful login payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoginResp {
    /// Bearer-like token used in the `Authorization` header.
    pub token: String,
    /// Newer server versions also return the active device key.
    #[serde(default)]
    pub device_key: Option<String>,
}

/// Registration request for `/api/auth/register`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisterReq {
    /// Username.
    pub username: String,
    /// Raw password; AList hashes it server-side for registration.
    pub password: String,
}

/// Request body for enabling 2FA.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Verify2FaReq {
    /// TOTP code entered by the user.
    pub code: String,
    /// Secret generated by `/api/auth/2fa/generate`.
    pub secret: String,
}

/// Payload returned by `/api/auth/2fa/generate`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Generate2FaResp {
    /// PNG QR code as a data URL.
    pub qr: String,
    /// TOTP secret.
    pub secret: String,
}

/// Permission bitmask scoped to a path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PermissionEntry {
    /// Path prefix, for example `/movies`.
    pub path: String,
    /// AList permission bitmask.
    pub permission: i32,
}

/// Current user payload returned by `/api/me`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserResp {
    /// Numeric user id.
    pub id: u64,
    /// Username.
    pub username: String,
    /// Server returns an empty string for current-user responses; older mounted
    /// clients may expose this field differently, so it stays optional.
    #[serde(default)]
    pub password: Option<String>,
    /// User base path.
    pub base_path: String,
    /// Role ids.
    pub role: Vec<i32>,
    /// Whether the account is disabled.
    pub disabled: bool,
    /// Legacy aggregate permission bitmask.
    pub permission: i32,
    /// SSO id. Current handlers serialize this as `sso_id`; empty string is common.
    #[serde(default)]
    pub sso_id: Option<String>,
    /// Whether TOTP is enabled.
    pub otp: bool,
    /// Role names added by current server versions.
    #[serde(default)]
    pub role_names: Vec<String>,
    /// Path-scoped permissions added by current server versions.
    #[serde(default)]
    pub permissions: Vec<PermissionEntry>,
}

/// Alias matching the `/api/me` endpoint name used by the client API.
pub type MeResp = UserResp;
