//! Data models for the `auth` OpenAPI group and `/api/me`.

use serde::{Deserialize, Deserializer, Serialize};

/// Login request for `/api/auth/login` and `/api/auth/login/hash`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoginReq {
    /// Username.
    pub username: String,
    /// Password, or static SHA-256 hash for `/login/hash`.
    pub password: String,
    /// Optional two-factor authentication code.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub otp_code: Option<String>,
}

/// Successful login payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoginResp {
    /// Bearer-like token used in the `Authorization` header.
    pub token: String,
    /// Newer server versions also return the active device key.
    #[serde(default)]
    pub device_key: Option<String>,
}

/// Registration request for `/api/auth/register`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RegisterReq {
    /// Username.
    pub username: String,
    /// Raw password; AList hashes it server-side for registration.
    pub password: String,
}

/// Request body for enabling 2FA.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Verify2FaReq {
    /// TOTP code entered by the user.
    pub code: String,
    /// Secret generated by `/api/auth/2fa/generate`.
    pub secret: String,
}

/// Payload returned by `/api/auth/2fa/generate`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Generate2FaResp {
    /// PNG QR code as a data URL.
    pub qr: String,
    /// TOTP secret.
    pub secret: String,
}

/// Permission bitmask scoped to a path.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PermissionEntry {
    /// Path prefix, for example `/movies`.
    pub path: String,
    /// AList permission bitmask.
    pub permission: i32,
}

/// Current user payload returned by `/api/me`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct UserResp {
    /// Numeric user id.
    pub id: u64,
    /// Username.
    pub username: String,
    /// Server returns an empty string for current-user responses; older mounted
    /// clients may expose this field differently, so it stays optional.
    #[serde(default)]
    pub password: Option<String>,
    /// User base path.
    pub base_path: String,
    /// Role ids.
    #[serde(deserialize_with = "deserialize_role_ids")]
    pub role: Vec<i32>,
    /// Whether the account is disabled.
    pub disabled: bool,
    /// Legacy aggregate permission bitmask.
    pub permission: i32,
    /// SSO id. Current handlers serialize this as `sso_id`; empty string is common.
    #[serde(default)]
    pub sso_id: Option<String>,
    /// Whether TOTP is enabled.
    pub otp: bool,
    /// Role names added by current server versions.
    #[serde(default)]
    pub role_names: Vec<String>,
    /// Path-scoped permissions added by current server versions.
    #[serde(default)]
    pub permissions: Vec<PermissionEntry>,
}

/// Alias matching the `/api/me` endpoint name used by the client API.
pub type MeResp = UserResp;

fn deserialize_role_ids<'de, D>(deserializer: D) -> Result<Vec<i32>, D::Error>
where
    D: Deserializer<'de>,
{
    #[derive(Deserialize)]
    #[serde(untagged)]
    enum RoleIds {
        Many(Vec<i32>),
        One(i32),
    }

    match RoleIds::deserialize(deserializer)? {
        RoleIds::Many(values) => Ok(values),
        RoleIds::One(value) => Ok(vec![value]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::common::ApiResponse;

    #[test]
    fn openapi_login_examples_match_models() {
        let req = LoginReq {
            username: "{{alist_username}}".to_string(),
            password: "{{alist_password}}".to_string(),
            otp_code: None,
        };
        assert_eq!(
            serde_json::to_value(&req).unwrap(),
            serde_json::json!({
                "username": "{{alist_username}}",
                "password": "{{alist_password}}"
            })
        );

        let resp: ApiResponse<LoginResp> = serde_json::from_value(serde_json::json!({
            "code": 200,
            "message": "success",
            "data": { "token": "abcd" }
        }))
        .unwrap();
        assert_eq!(resp.data.token, "abcd");
        assert_eq!(resp.data.device_key, None);
    }

    #[test]
    fn openapi_register_example_matches_model() {
        let req = RegisterReq {
            username: "string".to_string(),
            password: "string".to_string(),
        };
        assert_eq!(
            serde_json::to_value(&req).unwrap(),
            serde_json::json!({
                "username": "string",
                "password": "string"
            })
        );
    }

    #[test]
    fn openapi_two_factor_examples_match_models() {
        let generated: ApiResponse<Generate2FaResp> = serde_json::from_value(serde_json::json!({
            "code": 200,
            "message": "success",
            "data": {
                "qr": "data:image/png;base64,iVBORw0KGgoAAAANSUhE",
                "secret": "RPQZG4MDS3"
            }
        }))
        .unwrap();
        assert_eq!(generated.data.secret, "RPQZG4MDS3");

        let verify = Verify2FaReq {
            code: "123456".to_string(),
            secret: generated.data.secret,
        };
        assert_eq!(
            serde_json::to_value(&verify).unwrap(),
            serde_json::json!({
                "code": "123456",
                "secret": "RPQZG4MDS3"
            })
        );
    }

    #[test]
    fn openapi_me_example_matches_model() {
        let resp: ApiResponse<MeResp> = serde_json::from_value(serde_json::json!({
            "code": 200,
            "message": "success",
            "data": {
                "id": 2,
                "username": "admin",
                "password": "",
                "base_path": "/",
                "role": [2],
                "disabled": false,
                "permission": 65535,
                "sso_id": "",
                "otp": false,
                "role_names": ["admin"],
                "permissions": [{ "path": "/", "permission": 65535 }]
            }
        }))
        .unwrap();

        assert_eq!(resp.data.id, 2);
        assert_eq!(resp.data.username, "admin");
        assert_eq!(resp.data.password.as_deref(), Some(""));
        assert_eq!(resp.data.role, vec![2]);
        assert_eq!(resp.data.role_names, vec!["admin"]);
        assert_eq!(resp.data.permissions[0].permission, 65535);
    }

    #[test]
    fn me_role_accepts_legacy_single_integer() {
        let resp: ApiResponse<MeResp> = serde_json::from_value(serde_json::json!({
            "code": 200,
            "message": "success",
            "data": {
                "id": 2,
                "username": "admin",
                "password": "",
                "base_path": "/",
                "role": 2,
                "disabled": false,
                "permission": 65535,
                "sso_id": "",
                "otp": false,
                "role_names": ["admin"],
                "permissions": [{ "path": "/", "permission": 65535 }]
            }
        }))
        .unwrap();

        assert_eq!(resp.data.role, vec![2]);
    }
}
