name: Rust Code Style Format

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    name: Cargo Fmt
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format Code
        run: cargo fmt --check
