name: Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Cargo Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run unit tests
        run: cargo test --locked
